### PR TITLE
fix(core): resolve app freezing on web hot-reload and initial load

### LINKED ISSUE #54: Application freezes when reloading

### PR DESCRIPTION
**Pull request by JoachimTislov**
### Description
This PR resolves issue #54, where the Flutter Web application froze and rendered an empty white screen on initial load or during hot reload/refresh.

### Changes
- **CORS bypass**: Skipped the synchronous HTTP reachability check against the Auth Emulator on the `kIsWeb` environment. The browser otherwise threw a CORS exception that crashed `main()`.
- **AppCheck Re-initialization**: Wrapped `FirebaseAppCheck.instance.activate()` in a `try-catch` block with inline comments explaining why. On Web, the JS SDK retains state across hot-restarts. Calling `activate` a second time threw an "already initialized" exception that crashed the app.
- **Splash Screen Interceptor**: Introduced a lightweight `/splash` route in `router.dart`. When `GoRouter` runs on refresh, Firebase Auth takes >500ms to initialize. Previously, protected routes like `/dashboard` were attempting to load with `userId == null`, freezing the UI because they never fetched data. The interceptor safely parks the user on `/splash` and preserves their original deep-link (e.g. `/splash?target=/dashboard`) until Auth is ready.

### Related Issues
- Closes #54

### Testing
- Validated all tests via `make check`.
- Updated test cases to handle the new Splash route hand-off safely.

## Summary by CodeRabbit

* **New Features**
  * Splash screen during startup that preserves intended destination while auth initializes.

* **Bug Fixes**
  * Enforces providing an app flavor on non‑web runs.
  * Makes emulator/dev setup and App Check activation more resilient (failures warn instead of blocking).
  * Web reCAPTCHA key now comes from env with a dummy fallback; Android uses emulator-friendly provider when emulators are enabled.

* **Chores**
  * Supported flavors reduced to "development" and "production"; new run/build Make targets and emulator UI target added.

* **Documentation**
  * Added troubleshooting guide and expanded deployment/build links.

* **Tests**
  * Updated tests to match auth initialization and flavor changes.

### CODE REVIEW

**Review by JoachimTislov — COMMENTED** [review]
I have addressed the AI review feedback regarding the splash screen URL validation. The `/splash` route interceptor now explicitly checks that the `target` parameter is a valid internal relative path (`startsWith('/')`) and prevents infinite redirects (`!startsWith('/splash')`). These changes have been pushed to the PR branch and tested successfully.

**Comment by JoachimTislov** [comment]
I have reviewed and resolved all pending AI feedback and reviews:

1. **`lib/main.dart`**: 
   - Separated the try-catch blocks for emulator setup and Firebase App Check activation.
   - Used `String.fromEnvironment('RECAPTCHA_V3_SITE_KEY')` instead of a hardcoded string for the reCAPTCHA site key.
   - Configured production fallback logging to catch App Check activation errors.

2. **`lib/router.dart`**: 
   - Migrated the safety fallback from a `Future.delayed` to a cancelable `Timer` to prevent lingering executions after component disposal.
   - Strengthened target validation in the splash route to prevent protocol-relative and substring matching (e.g., `//evil.com`).
   - Cleaned up the initial redirect for root deep-links (`/`), omitting the `target` parameter entirely if it's identical to the root route.

3. **`tool/get_comments.dart`**:
   - Extracted `Process.run` operations into a reusable logging helper (`_runAndLog`).
   - Fixed incorrect casts for `result.stdout` to avoid crashes when dealing with null encoding defaults.
   - Fixed stderr payload interpolation bug within the logging call.

All checks, formatting and tests pass successfully (`make check`).

File: lib/main.dart [hunk 1]
```diff
@@ -55,7 +54,10 @@ void main() async {
     'Running in ${Config.environment} mode (Emulators: ${Config.useEmulators})',
   );
 
-  if (Config.useEmulators) {
+  // We skip this check on Web because making an HTTP GET request to the emulator
+  // from the browser triggers a CORS exception, which crashes the app before it
+  // can even render.
+  if (Config.useEmulators && !kIsWeb) {
     try {
```
Comment (JoachimTislov) [inline lib/main.dart:60]: need to confirm this

File: lib/main.dart [hunk 2]
```diff
@@ -82,13 +84,40 @@ void main() async {
...
+    }
+  } catch (e) {
+    if (Config.useEmulators) {
+      logger.w(
+        'Firebase/AppCheck initialization failed (likely due to hot restart): $e',
+      );
+    } else {
+      logger.e('Firebase/AppCheck initialization failed: $e');
+      // TODO: Forward to crash reporting hook (e.g. Crashlytics)
+    }
```
Comment (JoachimTislov) [inline lib/main.dart:112]: simplify, modify an object to run instance.active once

File: lib/main.dart [hunk 3]
```diff
@@ -23,18 +24,16 @@ const dummyOptions = FirebaseOptions(
...
-  'staging',
-  'production',
-];
+const List<String> supportedFlavors = <String>['development', 'production'];
 
 void main() async {
+  if (appFlavor == null && !kIsWeb) {
+    throw Exception(
+      'No app flavor provided. Please run the app using `make dev-android` or specify a flavor using `--flavor development`. See archive/issues/gradle-build-failed-apk-flavor.md for more info.',
+    );
```
Comment (JoachimTislov) [inline lib/main.dart]: make dev-android is outdated

Comment (JoachimTislov) [reply lib/main.dart]: android isn't a device

File: lib/main.dart (hunk 1 above)
Comment (JoachimTislov) [reply lib/main.dart:60]: works fine without !kIsWeb

File: lib/router.dart [hunk 4]
```diff
@@ -33,13 +34,23 @@ GoRouter createAppRouter(IAuthService authService) {
...
       final isLoggedIn = authService.getUserId() != null;
       final isAnonymousUser = authService.currentUser?.isAnonymous ?? false;
       final isAuthRoute = state.uri.path == '/auth';
       final isLandingRoute = state.uri.path == '/';
+      final isSplashRoute = state.uri.path == '/splash';
+
+      if (isSplashRoute) {
+        // Once initialized, proceed to the intended target.
+        // GoRouter will re-evaluate redirect for that target automatically.
+        return state.uri.queryParameters['target'] ?? '/';
```
[the remark this answers is not in the document]
Comment (JoachimTislov) [reply lib/router.dart]: diff is does the same...
